In [1]:
import cv2
import numpy as np
def showImage(img,title='Resized Window'):

    #define the screen resulation
    screen_res = 1280, 720
    scale_width = screen_res[0] / img.shape[1]
    scale_height = screen_res[1] / img.shape[0]
    scale = min(scale_width, scale_height)

    #resized window width and height
    window_width = int(img.shape[1] * scale)
    window_height = int(img.shape[0] * scale)

    #cv2.WINDOW_NORMAL makes the output window resizealbe
    cv2.namedWindow(title, cv2.WINDOW_NORMAL)

    #resize the window according to the screen resolution
    cv2.resizeWindow(title, window_width, window_height)

    cv2.imshow(title, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [1]:
import sudoku
import DataPrep
import tensorflow as tf

model = tf.keras.models.load_model('saved_model/my_model')
#model = DataPrep.build_and_train_model()
image = sudoku.InputImage('test','puzz1.jpg')
board = image.getBoard()
digit_recognizer = sudoku.DigitRecognizer(model)
#print(len(board.boxes))
for box in board.boxes:
    digit_recognizer.predict(box)
    print(f"{box.title} value {box.value}")

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "


row 0, col 0 value [9]
row 0, col 1 value [2]
row 0, col 2 value -1
row 0, col 3 value -1
row 0, col 4 value [1]
row 0, col 5 value -1
row 0, col 6 value [3]
row 0, col 7 value -1
row 0, col 8 value -1
row 1, col 0 value [8]
row 1, col 1 value [5]
row 1, col 2 value -1
row 1, col 3 value -1
row 1, col 4 value [9]
row 1, col 5 value -1
row 1, col 6 value -1
row 1, col 7 value [2]
row 1, col 8 value -1
row 2, col 0 value -1
row 2, col 1 value -1
row 2, col 2 value [3]
row 2, col 3 value -1
row 2, col 4 value -1
row 2, col 5 value -1
row 2, col 6 value -1
row 2, col 7 value -1
row 2, col 8 value -1
row 3, col 0 value -1
row 3, col 1 value -1
row 3, col 2 value -1
row 3, col 3 value -1
row 3, col 4 value -1
row 3, col 5 value [2]
row 3, col 6 value -1
row 3, col 7 value -1
row 3, col 8 value -1
row 4, col 0 value [3]
row 4, col 1 value -1
row 4, col 2 value -1
row 4, col 3 value -1
row 4, col 4 value -1
row 4, col 5 value [1]
row 4, col 6 value [6]
row 4, col 7 value -1
row 4, col 8 value 

In [3]:
image = sudoku.InputImage('test','puzz1.jpg')

In [4]:
#get board and boxes
board = image.getBoard()
print(len(board.boxes))

81


In [5]:
digit_recognizer = sudoku.DigitRecognizer(model)
test = digit_recognizer.predict(board.boxes[46]) #change variable name to raw_image
print(test)

[1]


In [13]:
test = ((digit_recognizer.preprocess(board.boxes[46].cv_image)))
showImage(test)

In [20]:
contours, heirarchy = cv2.findContours(test, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

In [33]:
contours[2]

array([[[14,  5]],

       [[13,  6]],

       [[12,  6]],

       [[10,  8]],

       [[10,  9]],

       [[ 9, 10]],

       [[ 9, 13]],

       [[10, 14]],

       [[10, 15]],

       [[13, 18]],

       [[18, 18]],

       [[19, 17]],

       [[20, 17]],

       [[21, 18]],

       [[20, 19]],

       [[20, 20]],

       [[18, 22]],

       [[14, 22]],

       [[11, 19]],

       [[10, 19]],

       [[ 9, 20]],

       [[10, 21]],

       [[10, 22]],

       [[12, 24]],

       [[13, 24]],

       [[14, 25]],

       [[18, 25]],

       [[23, 20]],

       [[23, 16]],

       [[24, 15]],

       [[24, 14]],

       [[23, 13]],

       [[23, 10]],

       [[22,  9]],

       [[22,  8]],

       [[20,  6]],

       [[19,  6]],

       [[18,  5]]], dtype=int32)

In [45]:
np.max(canvas)

255

In [48]:
canvas = np.zeros(test.shape,dtype=np.uint8)
canvas2 = np.zeros(test.shape,dtype=np.uint8)
cv2.drawContours(canvas,contours,len(contours) - 1, (1), thickness = cv2.FILLED)
canvas2 = cv2.bitwise_and(test,test,mask=canvas)

showImage(canvas2)

In [6]:
for box in board.boxes:
    digit_recognizer.predict(box)
    print(box.value)
    



[1]
[2]
-1
-1
[1]
-1
[1]
-1
-1
[8]
[5]
-1
-1
[1]
-1
-1
[2]
-1
-1
-1
[1]
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
[2]
-1
-1
-1
[1]
-1
-1
-1
-1
[1]
[6]
-1
-1
[1]
[1]
[7]
-1
-1
-1
[2]
[5]
-1
-1
-1
-1
[5]
-1
[1]
-1
[6]
[2]
-1
[8]
[5]
-1
-1
-1
[4]
-1
-1
-1
-1
[1]
-1
-1
-1
-1
[3]
-1


In [14]:
test = board.boxes[0].cv_image.shape

(112, 112)

In [21]:
test.shape

(1, 32, 32, 1)

In [22]:
model.predict(test)

array([[0., 0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
sero = np.ones((32,32))*255
test2 = sero-test.reshape((32,32))
test3 = cv2.dilate(test.reshape((32,32)), cv2.getStructuringElement(cv2.MORPH_CROSS,(1,1)),iterations=1)
ret, test3 = cv2.threshold(test3,200,255,cv2.THRESH_BINARY)

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 30, 30, 64)        640       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 15, 15, 64)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 13, 13, 128)       73856     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 6, 6, 128)        0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 4, 4, 256)         295168    
                                                                 
 conv2d_3 (Conv2D)           (None, 2, 2, 256)         5

In [10]:
digit_recognizer.model.predict(test.reshape(1,32,32,1))

array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 6.3313144e-24, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00]], dtype=float32)

In [11]:
!mkdir -p saved_model
model.save('saved_model/my_model')

INFO:tensorflow:Assets written to: saved_model/my_model/assets


In [7]:
test = board.boxes[0].cv_image
mask = digit_recognizer.getMask(test)
test = cv2.bitwise_and(test, test, mask=mask)
test = cv2.resize(test,(32,32),interpolation=cv2.INTER_AREA)
showImage(test[12:20,8:24])

In [20]:
showImage(test[12:20,8:24])

In [ ]:
test = DataPrep.preprocess(test)

In [ ]:

mask = digit_recognizer.getMask(test)
test2 = cv2.bitwise_and(test, test, mask=mask)
showImage(test2)

In [ ]:
np.max(test2*255)

In [ ]:
test3 = cv2.bitwise_not(test2*255)
showImage(test2*255)

In [ ]:
nine = DataPrep.get_rand_pic_of(9)

In [ ]:
x = DataPrep.ImageRetriever()
x.get(nine)
y = x.raw_image

In [ ]:
showImage(test2)

In [ ]:
import cv2
def showImage(img,title='Resized Window'):

    #define the screen resulation
    screen_res = 1280, 720
    scale_width = screen_res[0] / img.shape[1]
    scale_height = screen_res[1] / img.shape[0]
    scale = min(scale_width, scale_height)

    #resized window width and height
    window_width = int(img.shape[1] * scale)
    window_height = int(img.shape[0] * scale)

    #cv2.WINDOW_NORMAL makes the output window resizealbe
    cv2.namedWindow(title, cv2.WINDOW_NORMAL)

    #resize the window according to the screen resolution
    cv2.resizeWindow(title, window_width, window_height)

    cv2.imshow(title, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()



In [ ]:
test.reshape((32,32))

In [ ]:
test.shape

In [ ]:
import numpy as np
test = np.array(test,)

In [ ]:
test.reshape((32,32))

In [ ]:
test.shape

In [ ]:
showImage(test)